name: switchbox
description: Personal Media & Navigation Controller for Vehicle Use
publish_to: 'none'
version: 0.0.5+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^5.2.1
  permission_handler: ^11.0.1
  device_apps: ^2.2.0
  android_intent_plus: ^4.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Regular.ttf
          weight: 400